import type { LanguageOption, SiteContent } from "../guidekit/types.ts";

export const sampleLanguages = [
  { code: "zh-Hant", label: "繁體", shortLabel: "繁", htmlLang: "zh-Hant-TW", locale: "zh-TW" },
  { code: "zh-Hans", label: "简体", shortLabel: "简", htmlLang: "zh-Hans-CN", locale: "zh-CN" },
  { code: "ja", label: "日本語", shortLabel: "日", htmlLang: "ja", locale: "ja-JP" },
  { code: "ko", label: "한국어", shortLabel: "한", htmlLang: "ko", locale: "ko-KR" },
  { code: "en", label: "English", shortLabel: "EN", htmlLang: "en-US", locale: "en-US" },
] satisfies LanguageOption[];

const siteCopy: SiteContent["site"]["copy"] = {
  "zh-Hant": {
    metaTitle: "Guidekit Web 範例",
    metaDescription: "多地區導覽網站架構範例，使用可替換內容資料。",
    brand: "Guidekit",
    nav: [["profiles", "今日"], ["prices", "價格"], ["hotels", "地點"], ["contact", "聯絡"]],
  },
  "zh-Hans": {
    metaTitle: "Guidekit Web 示例",
    metaDescription: "多地区导览网站架构示例，使用可替换内容数据。",
    brand: "Guidekit",
    nav: [["profiles", "今日"], ["prices", "价格"], ["hotels", "地点"], ["contact", "联系"]],
  },
  ja: {
    metaTitle: "Guidekit Web サンプル",
    metaDescription: "差し替え可能なコンテンツで動く複数地域ガイドサイトのサンプルです。",
    brand: "Guidekit",
    nav: [["profiles", "本日"], ["prices", "料金"], ["hotels", "場所"], ["contact", "連絡"]],
  },
  ko: {
    metaTitle: "Guidekit Web 샘플",
    metaDescription: "교체 가능한 콘텐츠로 동작하는 다지역 가이드 사이트 샘플입니다.",
    brand: "Guidekit",
    nav: [["profiles", "오늘"], ["prices", "요금"], ["hotels", "장소"], ["contact", "연락"]],
  },
  en: {
    metaTitle: "Guidekit Web Sample",
    metaDescription: "A region-aware guide site sample powered by replaceable content.",
    brand: "Guidekit",
    nav: [["profiles", "Today"], ["prices", "Prices"], ["hotels", "Places"], ["contact", "Contact"]],
  },
};

const tokyoCopy = {
  "zh-Hant": {
    name: "東京",
    shortName: "東京",
    heroTitle: "東京即時導覽",
    heroCopy: "以地區和店家切換內容，讓同一套前端支援多個市場。",
    introTitle: "東京範例價格",
    introCopy: "這裡使用公開 sample data，展示多店家、多語與相簿流程。",
    hotelsTitle: "東京集合地點",
    hotelsCopy: "示範地點資訊如何跟著 region 切換。",
  },
  "zh-Hans": {
    name: "东京",
    shortName: "东京",
    heroTitle: "东京即时导览",
    heroCopy: "以地区和店家切换内容，让同一套前端支持多个市场。",
    introTitle: "东京示例价格",
    introCopy: "这里使用公开 sample data，展示多店家、多语与相册流程。",
    hotelsTitle: "东京集合地点",
    hotelsCopy: "示范地点信息如何跟随 region 切换。",
  },
  ja: {
    name: "東京",
    shortName: "東京",
    heroTitle: "東京ライブガイド",
    heroCopy: "地域と店舗で内容を切り替え、同じフロントエンドで複数市場に対応します。",
    introTitle: "東京サンプル料金",
    introCopy: "公開サンプルデータで、複数店舗、多言語、ギャラリーの流れを示します。",
    hotelsTitle: "東京の場所",
    hotelsCopy: "地域ごとに場所情報を切り替える例です。",
  },
  ko: {
    name: "도쿄",
    shortName: "도쿄",
    heroTitle: "도쿄 라이브 가이드",
    heroCopy: "지역과 매장 기준으로 콘텐츠를 전환해 하나의 프런트엔드로 여러 시장을 지원합니다.",
    introTitle: "도쿄 샘플 요금",
    introCopy: "공개 샘플 데이터로 다중 매장, 다국어, 갤러리 흐름을 보여줍니다.",
    hotelsTitle: "도쿄 장소",
    hotelsCopy: "지역에 따라 장소 정보가 전환되는 예시입니다.",
  },
  en: {
    name: "Tokyo",
    shortName: "Tokyo",
    heroTitle: "Tokyo Live Guide",
    heroCopy: "Switch content by region and shop while reusing the same frontend shell.",
    introTitle: "Tokyo Sample Pricing",
    introCopy: "Public sample data shows multi-shop filtering, language switching, and gallery flows.",
    hotelsTitle: "Tokyo Meeting Places",
    hotelsCopy: "Example place records demonstrate region-scoped content.",
  },
};

const osakaCopy = {
  "zh-Hant": {
    name: "大阪",
    shortName: "大阪",
    heroTitle: "大阪分區導覽",
    heroCopy: "新增地區只需要內容資料，不需要複製整個前端。",
    introTitle: "大阪範例價格",
    introCopy: "大阪範例驗證 region model 可以支援未來擴張。",
    hotelsTitle: "大阪集合地點",
    hotelsCopy: "地點、價格、profile 都歸屬於同一個 region。",
  },
  "zh-Hans": {
    name: "大阪",
    shortName: "大阪",
    heroTitle: "大阪分区导览",
    heroCopy: "新增地区只需要内容数据，不需要复制整个前端。",
    introTitle: "大阪示例价格",
    introCopy: "大阪示例验证 region model 可以支持未来扩张。",
    hotelsTitle: "大阪集合地点",
    hotelsCopy: "地点、价格、profile 都归属于同一个 region。",
  },
  ja: {
    name: "大阪",
    shortName: "大阪",
    heroTitle: "大阪エリアガイド",
    heroCopy: "新しい地域はコンテンツ追加だけで対応できます。前端を複製する必要はありません。",
    introTitle: "大阪サンプル料金",
    introCopy: "大阪サンプルで、region model が拡張に向いていることを確認します。",
    hotelsTitle: "大阪の場所",
    hotelsCopy: "場所、料金、プロフィールは同じ region に紐づきます。",
  },
  ko: {
    name: "오사카",
    shortName: "오사카",
    heroTitle: "오사카 지역 가이드",
    heroCopy: "새 지역은 콘텐츠 추가만으로 대응합니다. 프런트엔드를 복사하지 않습니다.",
    introTitle: "오사카 샘플 요금",
    introCopy: "오사카 샘플은 region model 이 확장에 적합한지 검증합니다.",
    hotelsTitle: "오사카 장소",
    hotelsCopy: "장소, 요금, 프로필은 같은 region 에 연결됩니다.",
  },
  en: {
    name: "Osaka",
    shortName: "Osaka",
    heroTitle: "Osaka Area Guide",
    heroCopy: "Add a new region with content data instead of copying the frontend.",
    introTitle: "Osaka Sample Pricing",
    introCopy: "The Osaka sample verifies the region model for future expansion.",
    hotelsTitle: "Osaka Meeting Places",
    hotelsCopy: "Places, prices, and profiles are scoped to the same region.",
  },
};

export const sampleContent: SiteContent = {
  site: {
    id: "guidekit-sample",
    defaultLanguage: "en",
    defaultRegionId: "tokyo",
    copy: siteCopy,
  },
  languages: sampleLanguages,
  regions: [
    { id: "tokyo", countryCode: "JP", timezone: "Asia/Tokyo", copy: tokyoCopy },
    { id: "osaka", countryCode: "JP", timezone: "Asia/Tokyo", copy: osakaCopy },
  ],
  shops: [
    {
      id: "tokyo-north",
      regionId: "tokyo",
      name: "North Star Desk",
      shortName: "North",
      contact: { phone: "+81-03-0000-0101", area: "Tokyo sample area", hours: "12:00-24:00" },
    },
    {
      id: "tokyo-east",
      regionId: "tokyo",
      name: "East Gate Desk",
      shortName: "East",
      contact: { phone: "+81-03-0000-0202", area: "Tokyo east sample area", hours: "14:00-02:00" },
    },
    {
      id: "osaka-central",
      regionId: "osaka",
      name: "Central Loop Desk",
      shortName: "Central",
      contact: { phone: "+81-06-0000-0101", area: "Osaka sample area", hours: "12:00-24:00" },
    },
  ],
  profiles: [
    {
      id: "sample-aoi",
      regionId: "tokyo",
      shopId: "tokyo-north",
      name: "Aoi",
      title: "Calm city guide",
      date: "2026-06-20",
      image: "sample-aoi-1",
      gallery: ["sample-aoi-1", "sample-aoi-2"],
      origin: "Tokyo",
      age: "24",
      height: "162 cm",
      tags: ["calm", "new", "north"],
      price: "Sample plan A",
      summary: "A compact sample profile used to verify card, modal, and gallery rendering.",
    },
    {
      id: "sample-mika",
      regionId: "tokyo",
      shopId: "tokyo-east",
      name: "Mika",
      title: "Evening schedule",
      date: "2026-06-20",
      image: "sample-mika-1",
      gallery: ["sample-mika-1", "sample-mika-2"],
      origin: "Tokyo",
      age: "26",
      height: "166 cm",
      tags: ["featured", "east"],
      price: "Sample plan B",
      summary: "A second Tokyo profile proves shop filters are data-driven.",
      isToday: false,
      lastSeen: "2026-06-18",
    },
    {
      id: "sample-rin",
      regionId: "osaka",
      shopId: "osaka-central",
      name: "Rin",
      title: "Central schedule",
      date: "2026-06-20",
      image: "sample-rin-1",
      gallery: ["sample-rin-1", "sample-rin-2"],
      origin: "Osaka",
      age: "23",
      height: "160 cm",
      tags: ["central", "sample"],
      price: "Sample plan C",
      summary: "An Osaka profile verifies that region switching changes visible content.",
    },
  ],
  hotels: [
    {
      id: "tokyo-hotel-1",
      regionId: "tokyo",
      name: "Tokyo Sample Place",
      area: "Central Tokyo",
      address: "1-1 Sample Street, Tokyo",
      image: "sample-tokyo-place",
    },
    {
      id: "osaka-hotel-1",
      regionId: "osaka",
      name: "Osaka Sample Place",
      area: "Central Osaka",
      address: "2-2 Sample Avenue, Osaka",
      image: "sample-osaka-place",
    },
  ],
  pricePlans: [
    { id: "tokyo-standard", regionId: "tokyo", name: "Tokyo Standard", note: "Sample only", rows: ["Short visit", "Standard visit", "Extended visit"] },
    { id: "osaka-standard", regionId: "osaka", name: "Osaka Standard", note: "Sample only", rows: ["Short visit", "Standard visit", "Extended visit"] },
  ],
  imageMap: {
    "sample-aoi-1": "https://picsum.photos/seed/guidekit-aoi-1/900/1200",
    "sample-aoi-2": "https://picsum.photos/seed/guidekit-aoi-2/900/1200",
    "sample-mika-1": "https://picsum.photos/seed/guidekit-mika-1/900/1200",
    "sample-mika-2": "https://picsum.photos/seed/guidekit-mika-2/900/1200",
    "sample-rin-1": "https://picsum.photos/seed/guidekit-rin-1/900/1200",
    "sample-rin-2": "https://picsum.photos/seed/guidekit-rin-2/900/1200",
    "sample-tokyo-place": "https://picsum.photos/seed/guidekit-tokyo-place/1200/800",
    "sample-osaka-place": "https://picsum.photos/seed/guidekit-osaka-place/1200/800",
  },
};
